use_frameworks!

target 'pod-deploy_Example' do
  pod 'pod-deploy', :path => '../'

  target 'pod-deploy_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
