default_platform(:ios)

platform :ios do

  desc "Test, lint pod and Build carthage."
  lane :test do
    test_example
    pod_lint
    carthage_build
  end

  desc "Cocoapods lint the pod for all platforms"
  private_lane :pod_lint do
    pod_lib_lint(allow_warnings: true)
  end

  desc "Test the example project"
  private_lane :test_example do  
    cocoapods(podfile: "./Example/Podfile",
              try_repo_update_on_error: true,
              silent: true
      )
    scan(workspace: "./Example/pod-deploy.xcworkspace",
              scheme: "pod-deploy-Example"
            )
  end

  desc "Carthage"
  private_lane :carthage_build do
  end

end
